/*
    To execute the interpreter on command line (outside the IDE):
        java -jar simple_expr.jar
 */
package parser;

public class Main
{
    public static void main(String[] args) {
        java.io.Reader reader = null;
        if(args.length == 0) {
            reader = new java.io.InputStreamReader(System.in);
        } else {
            if(args.length != 1) {
                System.out.println("Use : java -jar drp <file name>");
            } else {
                try {
                    java.io.FileInputStream stream = new java.io.FileInputStream(args[0]);
                    reader = new java.io.InputStreamReader(stream);
                } catch(java.io.FileNotFoundException e) {
                    System.out.println("File not found: \"" + args[0] + "\"");
                } catch(Exception e) {
                    System.out.println("Unexpected exception while opening file: " + e);
                }
            }
        }
        try {
            // Creates a scanner (generated by JFlex)
            Scanner scanner = new Scanner(reader);
            // Creates a parser (generated by CUP)
            Parser parser = new Parser(scanner);
            // Executes the analysis
            parser.parse();
        } catch(Exception e) {
            System.out.println("Unexpected exception during analysis: " + e);
        }
    }
}
